services:
  - type: web
    name: mtgit
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        scope: build
        sync: false
      - key: VITE_API_URL
        value: https://mtgit.onrender.com/trpc
      - key: BACKEND_URL
        value: https://mtgit.onrender.com
      - key: PORT
        value: "3000"
